In [121]:
import pandas as pd

In [122]:
# World Cup Matches
wcm = pd.read_csv("./WorldCupMatches.csv")

# World Cup Players
wcp = pd.read_csv("./WorldCupPlayers.csv")

# Cleaning World Cup Matches (wcm)

In [123]:
wcm.head(5)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [124]:
wcm.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

#### I'm not shure about   Stage, Assistant 1, Assistant 2

In [125]:
wcm.drop(["Win conditions", "RoundID", "MatchID", "Stage", "Assistant 1",
          "Assistant 2", "Home Team Initials", "Away Team Initials"], axis=1, inplace=True)

In [126]:
wcm.head(5)

,Year,Datetime,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,Referee
0,1930,13 Jul 1930 - 15:00,Pocitos,Montevideo,France,4,1,Mexico,4444.0,3,0,LOMBARDI Domingo (URU)
1,1930,13 Jul 1930 - 15:00,Parque Central,Montevideo,USA,3,0,Belgium,18346.0,2,0,MACIAS Jose (ARG)
2,1930,14 Jul 1930 - 12:45,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,24059.0,2,0,TEJADA Anibal (URU)
3,1930,14 Jul 1930 - 14:50,Pocitos,Montevideo,Romania,3,1,Peru,2549.0,1,0,WARNKEN Alberto (CHI)
4,1930,15 Jul 1930 - 16:00,Parque Central,Montevideo,Argentina,1,0,France,23409.0,0,0,REGO Gilberto (BRA)

In [127]:
len(wcm)

852

In [128]:
new_wcm = pd.DataFrame(columns=wcm.columns)
for i in wcm.index:
    if int(wcm.iloc[i]["Year"]) >= 2010:
        new_wcm = new_wcm.append(wcm.iloc[i])

In [129]:
wcm = new_wcm
len(wcm)

144

In [131]:
wcm = wcm.reset_index()
wcm.drop(["index", "level_0"], axis=1, inplace=True)

In [132]:
wcm.head(5)

,Year,Datetime,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance,Half-time Home Goals,Half-time Away Goals,Referee
0,2010,11 Jun 2010 - 16:00,Soccer City Stadium,Johannesburg,South Africa,1,1,Mexico,84490.0,0,0,Ravshan IRMATOV (UZB)
1,2010,11 Jun 2010 - 20:30,Cape Town Stadium,Cape Town,Uruguay,0,0,France,64100.0,0,0,NISHIMURA Yuichi (JPN)
2,2010,12 Jun 2010 - 13:30,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea Republic,2,0,Greece,31513.0,1,0,HESTER Michael (NZL)
3,2010,12 Jun 2010 - 16:00,Ellis Park Stadium,Johannesburg,Argentina,1,0,Nigeria,55686.0,1,0,Wolfgang STARK (GER)
4,2010,12 Jun 2010 - 20:30,Royal Bafokeng Sports Palace,Phokeng,England,1,1,USA,38646.0,1,1,SIMON Carlos (BRA)

# Cleaning World Cup Players (wcp)

In [134]:
wcp.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [135]:
wcp.drop(["Line-up", "Shirt Number", "Position", "Event"], axis=1, inplace=True)

In [136]:
wcp.head()

   RoundID  MatchID Team Initials           Coach Name       Player Name
0      201     1096           FRA  CAUDRON Raoul (FRA)       Alex THEPOT
1      201     1096           MEX     LUQUE Juan (MEX)   Oscar BONFIGLIO
2      201     1096           FRA  CAUDRON Raoul (FRA)  Marcel LANGILLER
3      201     1096           MEX     LUQUE Juan (MEX)      Juan CARRENO
4      201     1096           FRA  CAUDRON Raoul (FRA)   Ernest LIBERATI